### ISSUE TITLE
Migrate actions templates to Python 3

### ISSUE THREAD

**Issue by koenvervloesem** [snipsco/snips-actions-templates#14]
Python 2.7 will not be maintained after January 1, 2020. The actions templates should be migrated to Python 3. See https://github.com/snipsco/snips-app-template-py/issues/3.

**Comment by anthonyray** [comment]
Hello @koenvervloesem , 

The migration is underway ➡️ https://github.com/snipsco/snips-actions-templates/pull/15

Thanks for pointing this out !
